# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sebastian's Website
email: sebastianxcastaneda@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is Sebastian Castaneda's website in progress for now. 
  I will keep working on it until I am satisfied with my open-source website,
  which is powered by Jekyll and Gem.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  Boopit

# Build settings
markdown: kramdown

theme: jekyll-theme-slate